DefaultContentLanguage = "en"
title = "Julien Pivotto"
baseurl = "https://roidelapluie.github.io/"
SectionPagesMenu = "main"
Paginate = 5
PygmentsCodeFences = true
pygmentsstyle = "default"
cleandestinationdir = true
theme = "roidelapluie.be"

rssuri = "rss.xml"

[permalinks]
blog = "/blog/:year/:month/:day/:slug/"

[Languages]
[Languages.en]
[Languages.fr]
[[Languages.fr.menu.main]]
    name = "Ã€ propos"
    weight = -900
    identifier = "homepage"
    url = "/"

[[menu.main]]
    name = "About me"
    weight = -900
    identifier = "homepage"
    url = "/"


